/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.indioxd.perseus.view.telas;

import com.indioxd.perseus.core.entity.PessoaEntity;
import com.indioxd.perseus.core.service.ClienteService;
import com.indioxd.perseus.core.util.exception.NegocioException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author heto1
 */
public class TelaCadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroCliente() {
        initComponents();
        prepareMask();
    }
    public TelaCadastroCliente(int modo) {
        initComponents();
        this.modo = modo;
        prepareMask();
    }
    public TelaCadastroCliente(int modo, PessoaEntity cliente) {
        initComponents();
        this.modo = modo;
        this.cliente = cliente;
        carregaCliente();
        prepareMask();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRazao = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        lblFantasia = new javax.swing.JLabel();
        txtFantasia = new javax.swing.JTextField();
        lblCNPJ = new javax.swing.JLabel();
        lblIE = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        txtInscricao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtCadastro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNascto = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cboUF = new javax.swing.JComboBox<>();
        txtCnpj = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtID = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setMinimumSize(new java.awt.Dimension(700, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblRazao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRazao.setForeground(new java.awt.Color(180, 105, 255));
        lblRazao.setText("Razão Social");

        lblFantasia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFantasia.setForeground(new java.awt.Color(180, 105, 255));
        lblFantasia.setText("Fantasia");

        lblCNPJ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCNPJ.setForeground(new java.awt.Color(180, 105, 255));
        lblCNPJ.setText("CNPJ");

        lblIE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIE.setForeground(new java.awt.Color(180, 105, 255));
        lblIE.setText("Inscrição Estadual");

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(151, 74, 160));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/indioxd/perseus/img/check-mark_dim.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(180, 105, 255));
        jLabel5.setText("Logradouro");

        btnCancelar.setForeground(new java.awt.Color(151, 74, 160));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/indioxd/perseus/img/cancel_dim.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(180, 105, 255));
        jLabel6.setText("Tipo");

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pessoa Jurídica", "Pessoa Fisica" }));
        cboTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(180, 105, 255));
        jLabel7.setText("Data de Cadastro");

        txtCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCadastro.setText("00/00/0000");
        txtCadastro.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(180, 105, 255));
        jLabel8.setText("Data de Nascimento");

        jSeparator1.setEnabled(false);
        jSeparator1.setName(""); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(180, 105, 255));
        jLabel9.setText("Bairro");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(180, 105, 255));
        jLabel10.setText("Número");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(180, 105, 255));
        jLabel11.setText("Complemento");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(180, 105, 255));
        jLabel12.setText("CEP");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(180, 105, 255));
        jLabel13.setText("Cidade");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(180, 105, 255));
        jLabel14.setText("UF");

        cboUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "-----------", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));

        txtCnpj.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(180, 105, 255));
        jLabel15.setText("ID");

        txtID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtID.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtNascto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRazao)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtRazaoSocial)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFantasia)
                                    .addComponent(lblCNPJ)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblIE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtInscricao))
                                    .addComponent(txtLogradouro)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNumero))
                                    .addComponent(txtFantasia)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel12))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel14)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboUF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCEP))))))))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazao)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFantasia)
                    .addComponent(txtFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCNPJ)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIE)
                        .addComponent(txtInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtNascto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(cboUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(556, 442));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private PessoaEntity cliente;
    private int modo = 0;
    private MaskFormatter maskCNPJ;
    private MaskFormatter maskCPF;
    private MaskFormatter maskData;
    
    
    private void prepareMask(){
         try {
            maskCNPJ = new MaskFormatter("##.###.###/####-##");
            maskCNPJ.setPlaceholderCharacter('_');
            maskCPF = new MaskFormatter("###.###.###-##");
            maskCPF.setPlaceholderCharacter('_');
            txtCnpj.setFormatterFactory(new DefaultFormatterFactory(maskCNPJ));
            maskData = new MaskFormatter("##/##/####");
            maskData.setPlaceholderCharacter('_');
            txtNascto.setFormatterFactory(new DefaultFormatterFactory(maskData));
            
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void limpar(){
        //tipo
        cboTipo.setSelectedIndex(0);
        //data cadastro
        txtCadastro.setText("00/00/0000");
        //Razão Social
        txtRazaoSocial.setText("");
        lblRazao.setText("Razão Social");
        //fantasia
        txtFantasia.setText("");
        lblFantasia.setText("Fantasia");
        //cnpj
        txtCnpj.setValue(null);
        lblCNPJ.setText("CNPJ");
        //IE
        txtInscricao.setText("");
        lblIE.setText("Inscrição Estadual");
        //Data nascto
        txtNascto.setValue(null);
        txtNascto.setText("");
        //Endereco
        //logradouro
        txtLogradouro.setText("");
        //bairro
        txtBairro.setText("");
        //numero
        txtNumero.setText("");
        //complemento
        txtComplemento.setText("");
        //cep
        txtCEP.setText("");
        //cidade
        txtCidade.setText("");
        //UF
        cboUF.setSelectedIndex(0);
        
        modo = 0;
        cliente = null;
    }
    
    private void setPessoaJuridica(){
        lblRazao.setText("Razão Social");
        lblFantasia.setText("Fantasia");
        lblCNPJ.setText("CNPJ");
        lblIE.setText("Inscrição Estadual");
        //txtCnpj.setText("  .   .   /    -  ");
        txtCnpj.setValue(null);
        txtCnpj.setFormatterFactory(new DefaultFormatterFactory(maskCNPJ));
        
    }
    
    private void setPessoaFisica(){
        lblRazao.setText("Nome");
        lblFantasia.setText("Apelido");
        lblCNPJ.setText("CPF");
        lblIE.setText("RG");
        //txtCnpj.setText("   .   .   -  ");
        txtCnpj.setValue(null);
        txtCnpj.setFormatterFactory(new DefaultFormatterFactory(maskCPF));
    }
    
    private void carregaCliente(){
           
        PessoaEntity f = new PessoaEntity();
        ClienteService fs = new ClienteService();
        
        //tipo
        if(f.getTipo().equals("J")){
            cboTipo.setSelectedIndex(0);
            setPessoaJuridica();
        }else{
            cboTipo.setSelectedIndex(1);
            setPessoaFisica();
        }
        txtID.setText(f.getCodigo().toString());
        //data cadastro
        txtCadastro.setText(f.getDataCadastro().toString());
        //Razão Social
        txtRazaoSocial.setText(f.getRazaoSocial());
        //fantasia
        txtFantasia.setText(f.getFantasia());
        //cnpj
        txtCnpj.setValue(f.getCpfCnpj());
        //IE
        txtInscricao.setText(f.getInscricaoEstadual());
        //Data nascto
        txtNascto.setValue(f.getDataNascto());
        //Endereco
        //logradouro
        txtLogradouro.setText(f.getEnderecoLogradouro());
        //bairro
        txtBairro.setText(f.getEnderecoBairro());
        //numero
        txtNumero.setText(f.getEnderecoNumero());
        //complemento
        txtComplemento.setText(f.getEnderecoComplemento());
        //cep
        txtCEP.setText(f.getEnderecoCEP());
        //cidade
        txtCidade.setText(f.getEnderecoCidade());
        //UF
        cboUF.setSelectedItem(f.getEnderecoUF());
    }
   
    public void carregaClientePorID(Long codigoCliente){
    
    PessoaEntity f = null;
        try {
            f = new ClienteService().buscarClientePorID(codigoCliente);
                
            //tipo
            if(f.getTipo().equals("J")){
            cboTipo.setSelectedIndex(0);
            setPessoaJuridica();
            }else{
            cboTipo.setSelectedIndex(1);
            setPessoaFisica();
            }
            txtID.setText(f.getCodigo().toString());
            //data cadastro
            txtCadastro.setText(f.getDataCadastro().toString());
            //Razão Social
            txtRazaoSocial.setText(f.getRazaoSocial());
            //fantasia
            txtFantasia.setText(f.getFantasia());
            //cnpj
            txtCnpj.setValue(f.getCpfCnpj());
            //IE
            txtInscricao.setText(f.getInscricaoEstadual());
            //Data nascto
            txtNascto.setValue(f.getDataNascto());
            //Endereco
            //logradouro
            txtLogradouro.setText(f.getEnderecoLogradouro());
            //bairro
            txtBairro.setText(f.getEnderecoBairro());
            //numero
            txtNumero.setText(f.getEnderecoNumero());
            //complemento
            txtComplemento.setText(f.getEnderecoComplemento());
            //cep
            txtCEP.setText(f.getEnderecoCEP());
            //cidade
            txtCidade.setText(f.getEnderecoCidade());
            //UF
            cboUF.setSelectedItem(f.getEnderecoUF());
        } catch (NegocioException ex) {
            Logger.getLogger(TelaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            ex.ExibeErro();
        }
        
        this.cliente = f;
    
    }
    
  
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        PessoaEntity f = new PessoaEntity();
        ClienteService fs = new ClienteService();
        //tipo
        if(cboTipo.getSelectedIndex()==0){
            f.setTipo("J");
        }else{
            f.setTipo("F");
        }
        //data cadastro
        //Auto
        //Razão Social
        f.setRazaoSocial(txtRazaoSocial.getText());
        //fantasia
        f.setFantasia(txtFantasia.getText());
        //cnpj
        f.setCpfCnpj(txtCnpj.getText());
        //IE
        f.setInscricaoEstadual(txtInscricao.getText());
        //Data nascto
        if(!txtNascto.getText().equals("")&&txtNascto.getText()!=null){
            try {
                f.setDataNascto(new SimpleDateFormat("dd/MM/yyyy").parse(txtNascto.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(TelaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //Endereco
        //logradouro
        f.setEnderecoLogradouro(txtLogradouro.getText());
        //bairro
        f.setEnderecoBairro(txtBairro.getText());
        //numero
        f.setEnderecoNumero(txtNumero.getText());
        //complemento
        f.setEnderecoComplemento(txtComplemento.getText());
        //cep
        f.setEnderecoCEP(txtCEP.getText());
        //cidade
        f.setEnderecoCidade(txtCidade.getText());
        //UF
        f.setEnderecoUF(cboUF.getSelectedItem().toString());
        
        if(txtID.getText().equals("")){

            try {
                JOptionPane.showMessageDialog(rootPane, fs.salvarCliente(f));
               
            } catch (NegocioException ex) {
                Logger.getLogger(TelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
                ex.ExibeErro();
            }
        }
        else{
            f.setCodigo(cliente.getCodigo());
            try {
            JOptionPane.showMessageDialog(rootPane, fs.atualizaCliente(f));
            } catch (NegocioException ex) {
            
            Logger.getLogger(TelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
            ex.ExibeErro();
            }
            
            
        }
            limpar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        
        dispose();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cboTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipoItemStateChanged
        // TODO add your handling code here:
        if(cboTipo.getSelectedIndex()==0){
            setPessoaJuridica();
        }else{
            setPessoaFisica();
        }
    }//GEN-LAST:event_cboTipoItemStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        TelaCliente tf = new TelaCliente();
        tf.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /* java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        new TelaCadastroUsuario().setVisible(true);
        }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboTipo;
    private javax.swing.JComboBox<String> cboUF;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblFantasia;
    private javax.swing.JLabel lblIE;
    private javax.swing.JLabel lblRazao;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCadastro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtFantasia;
    private javax.swing.JFormattedTextField txtID;
    private javax.swing.JTextField txtInscricao;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JFormattedTextField txtNascto;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRazaoSocial;
    // End of variables declaration//GEN-END:variables
}
