/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.indioxd.perseus.view.telas;

import com.indioxd.perseus.core.entity.PessoaEntity;
import com.indioxd.perseus.core.entity.ProdutoEntity;
import com.indioxd.perseus.core.service.FornecedorService;
import com.indioxd.perseus.core.service.ProdutoService;
import com.indioxd.perseus.core.util.exception.NegocioException;
import java.text.NumberFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author heto1
 */
public class TelaCadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroProduto() {
        initComponents();
        carregaFornecedores();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRazao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblFantasia = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        lblCNPJ = new javax.swing.JLabel();
        lblIE = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cboFornecedor = new javax.swing.JComboBox<>();
        txtCusto = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtID = new javax.swing.JFormattedTextField();
        lblIE1 = new javax.swing.JLabel();
        txtVenda = new javax.swing.JTextField();
        lblIE2 = new javax.swing.JLabel();
        txtUnidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setMinimumSize(new java.awt.Dimension(700, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblRazao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRazao.setForeground(new java.awt.Color(180, 105, 255));
        lblRazao.setText("Descrição");

        lblFantasia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFantasia.setForeground(new java.awt.Color(180, 105, 255));
        lblFantasia.setText("Preço de Venda");

        lblCNPJ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCNPJ.setForeground(new java.awt.Color(180, 105, 255));
        lblCNPJ.setText("Preço de Custo");

        lblIE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIE.setForeground(new java.awt.Color(180, 105, 255));
        lblIE.setText("Fornecedor");

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(151, 74, 160));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/indioxd/perseus/img/check-mark_dim.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setForeground(new java.awt.Color(151, 74, 160));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/indioxd/perseus/img/cancel_dim.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtCusto.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(180, 105, 255));
        jLabel15.setText("ID");

        txtID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtID.setEnabled(false);

        lblIE1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIE1.setForeground(new java.awt.Color(180, 105, 255));
        lblIE1.setText("Estoque");

        lblIE2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIE2.setForeground(new java.awt.Color(180, 105, 255));
        lblIE2.setText("Unidade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(344, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRazao)
                            .addComponent(lblFantasia)
                            .addComponent(lblIE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescricao)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCNPJ))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblIE2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCusto, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtUnidade))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIE1)
                .addGap(60, 60, 60)
                .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCNPJ)
                    .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFantasia)
                    .addComponent(txtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIE)
                    .addComponent(cboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIE2)
                    .addComponent(txtUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIE1)
                    .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(586, 279));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private ProdutoEntity produto;
    private List<PessoaEntity> fornecedores;
    
    private final NumberFormat nf = NumberFormat.getCompactNumberInstance().getInstance();
    private final NumberFormat cf = NumberFormat.getCurrencyInstance();
          
    
    private void limpar(){
        //Descricao
        txtDescricao.setText("");
        //Estoque
        txtEstoque.setText("");
        //Custo
        txtCusto.setValue(null);
        //Fornecedor
        cboFornecedor.setSelectedIndex(0);
        txtVenda.setText("");
        produto = null;
    }
    
   
   
    
    private void carregaProduto(){
           
        ProdutoEntity f = new ProdutoEntity();
        ProdutoService fs = new ProdutoService();
        
        
        txtID.setText(f.getCodigo().toString());


        txtDescricao.setText(f.getDescricao());
        //fantasia
        txtEstoque.setText(f.getEstoque().toString());
        //cnpj
        txtCusto.setValue(f.getPrecoCusto().toString());
        //UF
        cboFornecedor.setSelectedItem(f.getFornecedor().getRazaoSocial());
    }
    
    private void carregaFornecedores(){
        try {
            fornecedores = new FornecedorService().listarFornecedor();
            cboFornecedor.addItem("");
            for (PessoaEntity f : fornecedores) {
               cboFornecedor.addItem(f.getRazaoSocial());
            }
            
            
        } catch (NegocioException ex) {
            Logger.getLogger(TelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
            ex.ExibeErro();
        }
    }
   
    public void carregaProdutoPorID(Long codigoProduto){
    
    ProdutoEntity p = null;
        try {
            p = new ProdutoService().buscarProdutoPorID(codigoProduto);
                
            
            txtID.setText(p.getCodigo().toString());
            txtDescricao.setText(p.getDescricao());
            txtEstoque.setText(p.getEstoque().toString().replace('.', ','));
            txtCusto.setText(p.getPrecoCusto().toString().replace('.', ','));
            txtVenda.setText(p.getPrecoVenda().toString().replace('.', ','));
            txtUnidade.setText(p.getUnidade());
            
            cboFornecedor.setSelectedItem(p.getFornecedor().getRazaoSocial());
        } catch (NegocioException ex) {
            Logger.getLogger(TelaCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
            ex.ExibeErro();
        }
        
        this.produto = p;
    
    }
    
  
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        ProdutoEntity p = new ProdutoEntity();
        ProdutoService ps = new ProdutoService();
        
        p.setDescricao(txtDescricao.getText());
        
        if(!txtVenda.getText().equals("")){
            p.setPrecoVenda(Double.parseDouble(txtVenda.getText().replace(',', '.')));
        }else{
            p.setPrecoVenda(0.0);
        }
        
        if(!txtCusto.getText().equals("")){
            p.setPrecoCusto(Double.parseDouble(txtCusto.getText().replace(',', '.')));
        }else{
            p.setPrecoCusto(0.0);
        }
        if(!txtEstoque.getText().equals("")){
            p.setEstoque(Double.parseDouble(txtEstoque.getText().replace(',', '.')));
        }else{
            p.setEstoque(0.0);
        }
        p.setUnidade(txtUnidade.getText());
        
        if(cboFornecedor.getSelectedIndex()>0){
            p.setFornecedor(fornecedores.get(cboFornecedor.getSelectedIndex()-1));
        }       
       
        
        if(txtID.getText().equals("")){

            try {
                JOptionPane.showMessageDialog(rootPane, ps.salvarProduto(p));
               
            } catch (NegocioException ex) {
                Logger.getLogger(TelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
                ex.ExibeErro();
            }
        }
        else{
            p.setCodigo(produto.getCodigo());
            try {
            JOptionPane.showMessageDialog(rootPane, ps.alterarProduto(p));
            } catch (NegocioException ex) {
            
            Logger.getLogger(TelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
            ex.ExibeErro();
            }
            
            
        }
            limpar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        
        dispose();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        TelaProduto tp = new TelaProduto();
        tp.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /* java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        new TelaCadastroUsuario().setVisible(true);
        }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboFornecedor;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblFantasia;
    private javax.swing.JLabel lblIE;
    private javax.swing.JLabel lblIE1;
    private javax.swing.JLabel lblIE2;
    private javax.swing.JLabel lblRazao;
    private javax.swing.JFormattedTextField txtCusto;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JFormattedTextField txtID;
    private javax.swing.JTextField txtUnidade;
    private javax.swing.JTextField txtVenda;
    // End of variables declaration//GEN-END:variables
}
