/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.indioxd.perseus.view.telas;

import com.indioxd.perseus.core.entity.UsuarioEntity;
import java.awt.Toolkit;

/**
 *
 * @author Huellinton
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        setIcon();
        setExtendedState(MAXIMIZED_BOTH);
    }
    
    
    public void carregaUsuario(UsuarioEntity u){
       if(u!=null){
           lblUsuario.setText("Usuário: "+u.getNome());
       }else{
           dispose();
       }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        lblUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuItemUsuario = new javax.swing.JMenuItem();
        mnuItemClientes = new javax.swing.JMenuItem();
        mnuItemFornecedor = new javax.swing.JMenuItem();
        mnuItemProduto = new javax.swing.JMenuItem();
        mnuVenda = new javax.swing.JMenu();
        mnuItemVenda = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perseus");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnClientes.setBackground(new java.awt.Color(51, 51, 51));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(180, 102, 255));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/indioxd/perseus/img/businessman_color_dim40.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setMargin(new java.awt.Insets(20, 20, 20, 20));
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnProduto.setBackground(new java.awt.Color(51, 51, 51));
        btnProduto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProduto.setForeground(new java.awt.Color(180, 102, 255));
        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/indioxd/perseus/img/open-box_color_dim40.png"))); // NOI18N
        btnProduto.setText("Produtos");
        btnProduto.setIconTextGap(10);
        btnProduto.setMargin(new java.awt.Insets(20, 20, 20, 20));
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });

        btnVendas.setBackground(new java.awt.Color(51, 51, 51));
        btnVendas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVendas.setForeground(new java.awt.Color(180, 102, 255));
        btnVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/indioxd/perseus/img/shopping-cart_color_dim40.png"))); // NOI18N
        btnVendas.setText("Iniciar Venda");
        btnVendas.setIconTextGap(10);
        btnVendas.setMargin(new java.awt.Insets(20, 20, 20, 20));
        btnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        lblUsuario.setText("Usuario: ");
        jToolBar1.add(lblUsuario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnClientes)
                        .addGap(18, 18, 18)
                        .addComponent(btnProduto)))
                .addContainerGap(486, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientes)
                    .addComponent(btnProduto))
                .addGap(18, 18, 18)
                .addComponent(btnVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Sistema");

        jMenuItem1.setText("Loja");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Configurações");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastros");

        mnuItemUsuario.setText("Usuário");
        mnuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(mnuItemUsuario);

        mnuItemClientes.setText("Clientes");
        mnuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemClientesActionPerformed(evt);
            }
        });
        jMenu2.add(mnuItemClientes);

        mnuItemFornecedor.setText("Fornecedores");
        mnuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemFornecedorActionPerformed(evt);
            }
        });
        jMenu2.add(mnuItemFornecedor);

        mnuItemProduto.setText("Produtos");
        mnuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuItemProduto);

        jMenuBar1.add(jMenu2);

        mnuVenda.setText("Venda");

        mnuItemVenda.setText("Consultar Vendas");
        mnuItemVenda.setToolTipText("");
        mnuItemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemVendaActionPerformed(evt);
            }
        });
        mnuVenda.add(mnuItemVenda);

        jMenuBar1.add(mnuVenda);

        jMenu3.setText("Ajuda");

        jMenuItem4.setText("Sobre");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemUsuarioActionPerformed
        // TODO add your handling code here:
        TelaUsuario tu = new TelaUsuario();
        tu.setVisible(true);
    }//GEN-LAST:event_mnuItemUsuarioActionPerformed

    private void mnuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemFornecedorActionPerformed
        // TODO add your handling code here:
        TelaFornecedor tf = new TelaFornecedor();
        tf.setVisible(true);
    }//GEN-LAST:event_mnuItemFornecedorActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        TelaCliente tc = new TelaCliente();
        tc.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void mnuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemClientesActionPerformed
        // TODO add your handling code here:
        TelaCliente tc = new TelaCliente();
        tc.setVisible(true);
    }//GEN-LAST:event_mnuItemClientesActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        // TODO add your handling code here:
        TelaProduto tp = new TelaProduto();
        tp.setVisible(true);
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void mnuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemProdutoActionPerformed
        // TODO add your handling code here:
        TelaProduto tp = new TelaProduto();
        tp.setVisible(true);
    }//GEN-LAST:event_mnuItemProdutoActionPerformed

    private void mnuItemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemVendaActionPerformed
        // TODO add your handling code here:
        TelaVenda tv = new TelaVenda();
        tv.setVisible(true);
    }//GEN-LAST:event_mnuItemVendaActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        // TODO add your handling code here:
        TelaNovaVenda tnv = new TelaNovaVenda();
        tnv.setVisible(true);
    }//GEN-LAST:event_btnVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        new TelaInicial().setVisible(true);
        }
        });*/
    }
    
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnVendas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem mnuItemClientes;
    private javax.swing.JMenuItem mnuItemFornecedor;
    private javax.swing.JMenuItem mnuItemProduto;
    private javax.swing.JMenuItem mnuItemUsuario;
    private javax.swing.JMenuItem mnuItemVenda;
    private javax.swing.JMenu mnuVenda;
    // End of variables declaration//GEN-END:variables
}
